### ISSUE TITLE
Complications with HDF5 dependency on mac silicon

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/hydrotools#198] opened 2022-06-08 18:32 UTC
This is a bit esoteric, but I'll document it here in case anyone else runs into it. Also note that the issue will probably resolve as the dependencies are updated.

The specific issue appears to be with the PyTables dependency, and specifically the HDF5 library within that dependency all when running on the Apple M1 chip. This StackOverflow issue summarizes things nicely: 
https://stackoverflow.com/questions/66147426/trying-to-install-pytables-for-python3

Ultimately the fix was to install pytables first, then to `pip install hydrotools`. The pytables installation requires explicit declaration of the hdf5 path: 
``` sh
brew install hdf5
HDF5_DIR=/Users/user/homebrew/opt/hdf5 pip install tables
pip install hydrotools
```

**Comment by hellkite500** [comment] 2022-06-10 22:31
How did you install HDF5?  Or did you install it prior to trying to instal this package?

**Comment by hellkite500** [comment] 2022-06-10 22:43
FWIW this has been actively worked in PyTables/PyTables#832 and my guess is that resolving your installation of HDF5 will get through this.

**Comment by jarq6c** [comment] 2022-06-21 18:35
@jameshalgren Thanks for reporting. Do you know if this issue also occurs when using conda or is it a pip specific problem?

**Comment by jarq6c** [comment] 2022-06-21 18:42
If the problem is pip specific, a conda-forge package might help resolve the issue.

https://github.com/conda-forge/staged-recipes
https://github.com/conda-incubator/grayskull

**Comment by hellkite500** [comment] 2022-10-06 18:43
It looks like a good build of hdf5 has hit homebrew for arm.  This error still creeps up, but can be resolved by installing hdf5 from homebrew
```sh
brew install hdf5

**Comment by aaraney** [comment] 2023-04-04 15:11
> and then installing tables and explicitly pointing to the brew hdf5 dir via an environment variable
> 
> ```shell
> HDF5_DIR=<homebrew_location>/opt/hdf5 pip install tables
> ```

To simplify this a bit, the following is equivalent (ignoring the `export`): 

```shell
export HDF5_DIR=$(readlink -f $(brew --prefix hdf5))
```

**Closed** 2023-06-08 13:49 UTC
Labels: documentation
